### PR TITLE
add close state

### PR DESCRIPTION
**Pull request by kekxv**
add close state

### CODE REVIEW

**Comment by gallickgunner** [comment]
Sorry but I don't get why do we need a close state? I modeled this after the ImGui approach to popups, so I really don't wanna change it because of confusion. You don't want to set `open = false` manually. It's false by default everytime you enter the code block. It goes to true once you hit the button to open the dialog and then goes back to false again the next frame.

**Comment by kekxv** [comment]
> Sorry but I don't get why do we need a close state? I modeled this after the ImGui approach to popups, so I really don't wanna change it because of confusion. You don't want to set `open = false` manually. It's false by default everytime you enter the code block. It goes to true once you hit the button to open the dialog and then goes back to false again the next frame.



Can you try the `ImGui::Begin` method?
i need isClose when use `ImGui::Begin`.

**Comment by gallickgunner** [comment]
> > Sorry but I don't get why do we need a close state? I modeled this after the ImGui approach to popups, so I really don't wanna change it because of confusion. You don't want to set `open = false` manually. It's false by default everytime you enter the code block. It goes to true once you hit the button to open the dialog and then goes back to false again the next frame.
> 
> Can you try the `ImGui::Begin` method? i need isClose when use `ImGui::Begin`.

That's for windows, this file dialog is modelled as a popup modal. Why exactly do you need to use `ImGui::Begin` for this file dialog? If you can post your usecase, perhaps I could help modify it to fit the popup modal structure

**Comment by kekxv** [comment]
I find the cause,`ImGui::OpenPopup` and `showFileDialog` not one `ImGui::Begin`.

is working when one `ImGui::Begin`.

In addition, the previous statement(https://github.com/gallickgunner/ImGui-Addons/pull/44#issuecomment-976536443) is wrong, it should be `ImGui::Button` not `ImGui::Begin`.

**Pull request closed without merging**
