### PR TITLE
Fixes compile bug for imgui v1.80

### PR DESCRIPTION
**Pull request by RicoP**

### CODE REVIEW

**Comment by gallickgunner** [comment]
@RicoP - Thanks for the upgrade to 1.80. I think you forgot to update the submodule as well, maybe that's why travisCI is throwing build errors. Can you update the submodule as well?

**Comment by Gargaj** [comment]
The .yaml is gonna need `imgui/backends/imgui_impl_opengl3.cpp` and `imgui/backends/imgui_impl_sdl.cpp` added otherwise the builds will fail.

**Comment by RicoP** [comment]
> 
> 
> The .yaml is gonna need `imgui/backends/imgui_impl_opengl3.cpp` and `imgui/backends/imgui_impl_sdl.cpp` added otherwise the builds will fail.

Thank you! I got a bit frustrated because I couldn't get it to run... 

Now Linux builds fine but on mac there is still the error


	Error:
	homebrew-core is a shallow clone.
	homebrew-cask is a shallow clone.
	To `brew update`, first run:
	git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
	git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
	These commands may take a few minutes to run due to the large size of the repositories.
	This restriction has been made on GitHub's request because updating shallow
	clones is an extremely expensive operation due to the tree layout and traffic of
	Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
	automatically to avoid repeatedly performing an expensive unshallow operation in
	CI systems (which should instead be fixed to not use shallow clones). Sorry for
	the inconvenience!
	Failed during: /usr/local/bin/brew update --force --quiet



But I don't think that's my mistake 🤔

**Comment by Gargaj** [comment]
Yeah it's the Mac build running a deprecated Homebrew instaler: https://travis-ci.com/github/gallickgunner/ImGui-Addons/jobs/481090783#L88

**Comment by RicoP** [comment]
> 
> 
> Yeah it's the Mac build running a deprecated Homebrew instaler: https://travis-ci.com/github/gallickgunner/ImGui-Addons/jobs/481090783#L88

Guess that would also fail on master anyway. Guess @gallickgunner can merge?

**Comment by gallickgunner** [comment]
> Yeah it's the Mac build running a deprecated Homebrew instaler: https://travis-ci.com/github/gallickgunner/ImGui-Addons/jobs/481090783#L88

Thanks for the info. I really don't know how to make travis-ci work and I was hesitating to merge since I didn't have any other way to check if it'd work on other platforms. So how do I go about updating the Homebrew installer?

@RicoP - Yea, thanks for the contribution, merging for now since it's working on Linux.

**Comment by Gargaj** [comment]
According to https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos you could just list the packages you want installed in the YAML.

**Comment by gallickgunner** [comment]
> According to https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos you could just list the packages you want installed in the YAML.

So in essence, I need to remove the `before_install` part from the macOS portion and replace it with
```
addons:
  homebrew:
    packages:
    - sdl2
    -glew
    update: true
 ```

**Comment by Gargaj** [comment]
And the Xcode version: https://github.com/gallickgunner/ImGui-Addons/pull/25

**Pull request merged**
